##################################################################
# H2 Properties 

jdbcServerUrl: jdbc:h2:tcp://localhost:9092/nessus

jdbcUrl: jdbc:h2:file:/var/h2db/nessus

jdbcUser: h2

jdbcPassword:

